apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  ports:
    - port: 27017  #Service port
      name: mongodb-port
      protocol: TCP
      targetPort: 27017 #target port of the pod
  clusterIP: None # 👈 Crucial: Makes the service headless
  selector:
    project: roboshop
    component: mongodb
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  ports:
    - port: 27017 #Service port
      name: mongodb-port
      protocol: TCP
      targetPort: 27017 #target port of the pod
  selector:
    project: roboshop
    component: mongodb
    tier: db
