apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-ebs
provisioner: ebs.csi.aws.com # Tells K8s to use the AWS EBS CSI driver
volumeBindingMode: WaitForFirstConsumer # CRITICAL: Delays EBS volume creation until the Pod is scheduled, ensuring it is created in the exact same Availability Zone (AZ) as the worker node.
allowVolumeExpansion: true # Allows you to scale up the volume size later without deleting the resource
parameters:
  type: gp3
