- name: Configure Froneend Server
  hosts: frontend
  become: yes
  serial: 2
  tasks:
    - name: ping module
      ping:
    - name: install nginx server
      package:
        name: nginx
        state: present
