apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
type: Opaque
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "eWVzCg=="
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  ports:
    - port: 3306  #Service port
      name: mysql-port
      protocol: TCP
      targetPort: 3306 #target port of the pod
  clusterIP: None # 👈 Crucial: Makes the service headless
  selector:
    project: roboshop
    component: mysql
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  ports:
    - port: 3306 #Service port
      name: mysql-port
      protocol: TCP
      targetPort: 3306 #target port of the pod
  selector:
    project: roboshop
    component: mysql
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  serviceName: "mysql-headless" # 👈 Must perfectly match your Headless Service name
  replicas: 1
  selector:
    matchLabels:
      project: roboshop # 👈 Must perfectly match your Pod template labels
      component: mysql
      tier: db
  template:
    metadata:
      labels:
        project: roboshop  #👈 Must perfectly match your StatefulSet selector
        component: mysql
        tier: db
    spec:
      containers:
        - name: mysql
          image: pandalapadu/mysql:4.0.0
          args: ["--default-authentication-plugin=mysql_native_password"]
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "RoboShop@1"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: www
              mountPath: /var/lib/mysql # Path inside the container
  # Automatically provisions a separate persistent volume for each pod ordinal
  volumeClaimTemplates:  # without pvc written in the pod spec, the statefulset will create a pvc for each pod
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs" # ⚠️ Replace with your active storage class (e.g., efs-dynamic-sc)
        resources:
          requests:
            storage: 1Gi
