apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  ports:
    - port: 5672  #Service port
      name: rabbitmq-port
      protocol: TCP
      targetPort: 5672 #target port of the pod
  clusterIP: None # 👈 Crucial: Makes the service headless
  selector:
    project: roboshop
    component: rabbitmq
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  ports:
    - port: 5672 #Service port
      name: rabbitmq-port
      protocol: TCP
      targetPort: 5672 #target port of the pod
  selector:
    project: roboshop
    component: rabbitmq
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  serviceName: "rabbitmq-headless" # 👈 Must perfectly match your Headless Service name
  replicas: 1
  selector:
    matchLabels:
      project: roboshop # 👈 Must perfectly match your Pod template labels
      component: rabbitmq
      tier: db
  template:
    metadata:
      labels:
        project: roboshop  #👈 Must perfectly match your StatefulSet selector
        component: rabbitmq
        tier: db
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3
          ports:
            - containerPort: 5672
              name: rabbitmq
          volumeMounts:
            - name: www
              mountPath: /var/lib/rabbitmq # Path inside the container
  # Automatically provisions a separate persistent volume for each pod ordinal
  volumeClaimTemplates:  # without pvc written in the pod spec, the statefulset will create a pvc for each pod
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs" # ⚠️ Replace with your active storage class (e.g., efs-dynamic-sc)
        resources:
          requests:
            storage: 1Gi
