- name: Installing and Starting NGINX  
  hosts: frontend
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: nginx starting 
      service:
        name: nginx 
        state: started 
    


