- name: Ansible filters discussions
  hosts: frontend
  become: yes
  vars:
    topics: Linux and shell and Ansible and Terraofrm
  tasks:
    - name: Convert String to list
      debug:
        msg: "Topics are: {{ topics | split('and') }} "