- name: Ansible filters discussions
  hosts: frontend
  become: yes
  vars:
    topics: Linux , shell , Ansible , Terraofrm
    tagsMap:
      name: Ansible
      project: Roboshop
      environment: Dev
    tagslist:
      [{'key': 'name', 'value': 'Ansible'}, {'key': 'project', 'value': 'Roboshop'}, {'key': 'environment', 'value': 'Dev'}]
    first_name: venkatreddy
  tasks:
    - name: Convert String to list
      debug:
        msg: "Topics are: {{ topics | split(',') }} "
    - name: set default values
      debug:
        msg: "Hi {{ GREETINGS | default('Good Morning') }}"
    - name: Convert Map to list
      debug:
        msg: "Converting Map to list {{ tagsMap | dict2items }}"
    - name: Convert list to Map
      debug:
        msg: "Converting list to Map {{ tagslist | items2dict }}"
    - name: Name conver to UPPERcase
      debug:
        msg: "Conver name to upper: {{ first_name | upper }}"