- name: Ansible filters discussions
  hosts: frontend
  become: yes
  vars:
    topics: Linux , shell , Ansible , Terraofrm
    tagsMap:
      name: Ansible
      project: Roboshop
      environment: Dev
  tasks:
    - name: Convert String to list
      debug:
        msg: "Topics are: {{ topics | split(',') }} "
    - name: set default values
      debug:
        msg: "Hi {{ GREETINGS | default('Good Morning') }}"
    - name: Convert Map to list
      debug:
        msg: "Converting Map to list {{ tagsMap | dict2item }}"