#!/bin/bash
- name: Working on Shell module vs Command module in ansible
  hosts: frontend
  become: yes
  tasks:
    - name: command module testing
      shell: cat /etc/passwd | grep root
      register: user_output
    - name: printing user output values
      debug:
        msg: "users output is: {{ user_output }}"