[frontend]
172.31.28.183 ;COURSE="Variables from Ansible Server to "

[catalogue]
172.31.21.85

[user]
172.31.21.86

[cart]
172.31.21.86

[roboshop:children]
frontend
catalogue
user
cart

[local]
localhost

;[local:vars]
;COURSE= "Ansible"
;TRAINER= "venkat"
;DURATION= "150HRs"

;[frontend:vars]
;COURSE= "Devops with Azure and AWS"
;TRAINER= "tanishka reddy"
;DURATION= "190HRs"