apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  ports:
    - port: 27017  #Service port
      name: mongodb-port
      protocol: TCP
      targetPort: 27017 #target port of the pod
  clusterIP: None # 👈 Crucial: Makes the service headless
  selector:
    project: roboshop
    component: mongodb
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  ports:
    - port: 27017 #Service port
      name: mongodb-port
      protocol: TCP
      targetPort: 27017 #target port of the pod
  selector:
    project: roboshop
    component: mongodb
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  serviceName: "mongodb-headless" # 👈 Must perfectly match your Headless Service name
  replicas: 1
  selector:
    matchLabels:
      project: roboshop # 👈 Must perfectly match your Pod template labels
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop  #👈 Must perfectly match your StatefulSet selector
        component: mongodb
        tier: db
    spec:
      containers:
        - name: mongodb
          image: pandalapadu/mongodb:4.0.0
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: www
              mountPath: /data/db # Path inside the container
  # Automatically provisions a separate persistent volume for each pod ordinal
  volumeClaimTemplates:  # without pvc written in the pod spec, the statefulset will create a pvc for each pod
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs" # ⚠️ Replace with your active storage class (e.g., efs-dynamic-sc)
        resources:
          requests:
            storage: 1Gi
