pipeline {

    agent {
        node {
            label 'ROBOSHOP'
        }
    }

    options {
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    stages {

        stage('Build') {
            steps {
                sh '''
                    echo "=============================="
                    echo "Catalogue Build Stage"
                    echo "=============================="
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    echo "=============================="
                    echo "Catalogue Test Stage"
                    echo "=============================="
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    echo "=============================="
                    echo "Catalogue Deploy Stage"
                    echo "=============================="
                '''
            }
        }
    }

    post {
        always {
            echo "it will run always"
        }

        success {
            echo "I will run only success"
        }

        failure {
            echo "I will run if build failed"
        }
    }
}