pipeline {
    agent {
        node {
            label 'ROBOSHOP'
        }
    }
    environment {
        acc_id = "453388807064"
        project = "roboshop"
        component = "catalogue"
    }


    options {
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    stages {
        stage('Read Version') {
            steps {
                script {
                    def packageJson = readJSON file: '8-Jenkins/8-01-catalogue/package.json'

                    def appName    = packageJson.name
                    def appVersion = packageJson.version

                    echo "Application: ${appName}"
                    echo "Version: ${appVersion}"

                    env.APP_NAME    = appName
                    env.APP_VERSION = appVersion
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('8-Jenkins/8-01-catalogue') {
                    sh 'npm install'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('8-Jenkins/8-01-catalogue') {
                    sh "docker build -t ${env.APP_NAME}:${env.APP_VERSION} ."
                    // sh 'npm test' // Uncomment if test scripts exist in package.json
                }
            }
        }

        stage('ECR Image push') {
            steps {
                script {
                    // in this block we get aws authentication
                    withAWS(credentials: 'aws-credentials', region: 'us-east-1') {
                        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${acc_id}.dkr.ecr.us-east-1.amazonaws.com
                        docker build -t  ${acc_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${component}:${appVersion} .
                        docker push ${acc_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${component}:${appVersion}
                    }
                }
            }
        }
    }

    post {
        always {
            echo "it will run always"
        }
        success {
            echo "I will run only success"
        }
        failure {
            echo "I will run if build failed"
        }
    }
}