pipeline {
    agent {
        node {
            label 'ROBOSHOP'
        }
    }

    // tools {
    //     nodejs 'Node-20' // If using the Jenkins NodeJS tool plugin
    // }

    options {
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    stages {
        stage('Read Version') {
            steps {
                script {
                    def packageJson = readJSON file: '8-Jenkins/8-01-catalogue/package.json'

                    def appName    = packageJson.name
                    def appVersion = packageJson.version

                    echo "Application: ${appName}"
                    echo "Version: ${appVersion}"

                    env.APP_NAME    = appName
                    env.APP_VERSION = appVersion
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('8-Jenkins/8-01-catalogue') {
                    sh 'npm install'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('8-Jenkins/8-01-catalogue') {
                    sh ' docker build -t catalogue: ${appVersion} .'
                    // sh 'npm test' // Uncomment if test scripts exist in package.json
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying ${env.APP_NAME} version ${env.APP_VERSION}..."
            }
        }
    }

    post {
        always {
            echo "it will run always"
        }
        success {
            echo "I will run only success"
        }
        failure {
            echo "I will run if build failed"
        }
    }
}