apiVersion: v1
kind: Pod
metadata: 
  name: nginx ## Pod name
  lables:
    project: roboshop
    environment: dev
    purpose: poc
spec:
  containers:
    - name: nginx  ## Container name 
      image: nginx
