apiVersion: v1
kind: Pod
metadata:
  name: nginx   ## Pod name
  labels:
    project: roboshop
    environment: dev
    purpose: poc
spec:
  containers:
    - name: nginx  ## Container name
      image: nginx 
        
    - name: almalinux
      image: almalinux:9
