apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: project
        value: "roboshop"
      - name: course
        value: "DevOps"