MONGODB_HOST: mongodb-{{ env }}.azdevopsvenkat.site
REDIS_HOST: redis-{{ env }}.azdevopsvenkat.site
MYSQL_HOST: mysql-{{ env }}.azdevopsvenkat.site 
RABBITMQ_HOST: rabbitmq-{{ env }}.azdevopsvenkat.site 
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.azdevopsvenkat.site
USER_HOST: user.backend-alb-{{ env }}.azdevopsvenkat.site
CART_HOST: cart.backend-alb-{{ env }}.azdevopsvenkat.site
SHIPPING_HOST: shipping.backend-alb-{{ env }}.azdevopsvenkat.site
PAYMENT_HOST: payment.backend-alb-{{ env }}.azdevopsvenkat.site