MYSQL_ROOT_PASSWORD: RoboShop@1 #manuval method 
#root_password: "{{ lookup('amazon.aws.aws_secret', 'roboshop/mysql_root_password', region='us-east-1') | from_json }}"
##this is used for password set up from AWS secret manger instead of passing from local