- name: demo on variable files
  hosts: local
  connection: local
  vars_files:
  - course.yml
  tasks:
    - name: print variable information from another file
      debug:
        msg: "Hi I am learing {{ COURSE }}, from {{ TRAINER }}, class hours  is {{ DURATION }} "