- name: demo for sensitive variable hiding 
  hosts: local
  connection: local
  vars_prompt:
    - name: user_name
      prompt: "Please Enter your user name"
      private: false

    - name: password
      prompt: "Enter the password"
      private: true
  tasks:
  - name: print information
    debug:
      msg: "i am using the Username is :: {{ user_name }} and password is::: {{ password }}"