- name: demo on inventery variable files
  hosts: frontend
  tasks:
    - name: print variable 
      debug:
        msg: "Hi I am learing {{ COURSE }}, from {{ TRAINER }}, class hours  is {{ DURATION }} and key used is {{ common_key }} from all.yml file"