- name: installing multipple packages 
  hosts: frontend
  become: yes
  tasks:
    - name: installing multiple packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - git 
        - htop
        - mysql