#!/bin/bash
- name: Working on Shell module vs Command module in ansible
  hosts: frontend
  become: yes
  tasks:
    - name: command module testing
      shell: cat /etc/passwd | grep root
      register: user_output
    - name: printing user output values
      debug:
        msg: " {{ user_output }}"
    - name: list files in command line
      shell: ls -ltr > /tmp/files.txt