apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mysql
  # Pod
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mysql
    spec:
      serviceAccountName: roboshop-mysql
      initContainers:
      - name: secret-reader
        image: amazon/aws-cli
        command:
        - sh
        - -c
        - |
            aws secretsmanager get-secret-value --secret-id \
            roboshop/dev/mysql_dev_root_password --query SecretString \
            --output text | jq -r '.MYSQL_ROOT_PASSWORD' > /secrets/mysql-secret.txt
            echo "Secret fetched successfully"
            cat /secrets/mysql-secret.txt # just for testing, we should not do this
        volumeMounts:
        - name: mysql-secret
          mountPath: /secrets
      containers:
      - name: mysql
        image: pandalapadu/mysql:4.0.0
        args: ["--mysql-native-password=ON"]
        volumeMounts:
        - name: mysql-secret
          mountPath: /secrets
      volumes:
      - name: mysql-secret
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  selector:
    project: roboshop
    tier: db
    component: mysql
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # container port