name: roboshop
services:
  mongodb:  ###Service-1
    build: ./1-MongoDB
    image: pandalapadu/mongodb:v1 #docker build -t pandalapadu/mongodb:v1
    container_name: mongodb #docker run -d --network roboshop pandalapadu/mongodb:v1
  catalogue:   ###Service-2
    build: ./2-catalogue
    image: pandalapadu/catalogue:v1 #docker build -t pandalapadu/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  frontend:  ###Service-3
    build: ./3-frontend
    image: pandalapadu/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
  user:    ###Service-4
    build: ./4-user
    image: pandalapadu/user:v1
    container_name: user
    environment:
       MONGO: true
       REDIS_URL: 'redis://redis:6379'
       MONGO_URL: "mongodb://mongodb:27017/users"
    depends_on:
      - redis
      - mongodb
  cart:    ###Service-6
    build: ./5-cart
    image: pandalapadu/cart:v1
    container_name: cart
    environment:
       REDIS_HOST: redis
       CATALOGUE_HOST: catalogue
       CATALOGUE_PORT: 8080
    depends_on:
      - redis
      - catalogue
  redis:   ###Service-5
    image: redis:7
    container_name: redis
  mysql: ###Service-7
    image: pandalapadu/mysql:v1
    build: ./6-mysql
    container_name: mysql
    command: --mysql-native-password=ON --innodb-lock_wait_timeout=120
    environment:
      MYSQL_ROOT_PASSWORD: "RoboShop@1"

networks:
  default: ## by default all files/service use this network 
    name: roboshop
    driver: bridge
    external: false  # if True it created manuvally --> if FALSE docker automatically created this network
