apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels related to deployment resource
  labels:
    project: roboshop
    tier: frontend
    component: frontend
spec:
  replicas: 7
  selector:
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
  # Pod
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
