          # Manual EKS operation
          #        │
          #        └── eksctl create cluster
          #                │
          #                ├── Control Plane
          #                │
          #                └── Managed Node Group
          #                     ├── t3.small
          #                     └── t3.small


# eksctl create cluster --config-file=eksctl.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: roboshop
  region: us-east-1
autoModeConfig:
  enabled: false
managedNodeGroups:
  - name: managed
    instanceTypes:
      - t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    spot: true

#####
#for creation of cluster --> eksctl create cluster -f eksctl.yaml
#2.Configure kubectl --> aws eks update-kubeconfig --region us-east-1 --name roboshop
#3.Verify everything -> aws eks describe-cluster --region us-east-1 --name roboshop --query 'cluster.status'
# Then --> eksctl get nodegroup --cluster roboshop --region us-east-1
# kubectl get nodes