apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels related to deployment resource
  labels:
    project: roboshop
    tier: frontend
    component: frontend
    purpose: deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
      purpose: deployment
  # Pod
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  # servicer labels
  labels:
    project: roboshop
    tier: frontend
    component: frontend
    purpose: deployment
spec:
  # Service uses the below labels to select the pods
  selector:
    project: roboshop
    tier: frontend
    component: frontend
    purpose: deployment
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.port }} # service port
      targetPort: {{ .Values.deployment.port }} # container port