apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
  labels:
    project: roboshop
    component: node-selector
spec:
  containers:
    - name: node-selector-container
      image: nginx
  nodeSelector:
    project: roboshopp