apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity-pod
  labels:
    project: roboshop
    component: node-anti-affinity
spec:
  containers:
    - name: node-anti-affinity-container
      image: nginx
  affinity:
    nodeAffinity: #this is Hard rule must be satisfied for the pod to be scheduled on the node.
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - us-east-1a
                  - us-east-1c
      preferredDuringSchedulingIgnoredDuringExecution: #this is Soft rule, if the node has this label, the pod will be scheduled on that node. If not, it will be scheduled on any other node.
        - weight: 2  #this is weight preference, higher weight means higher preference. If the node has this label, the pod will be scheduled on that node. If not, it will be scheduled on any other node.
          preference:
            matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: NotIn #this is Anti-affinity rule, if the node has this label, the pod will not be scheduled on that node. If not, it will be scheduled on any other node.
                values:
                  - us-east-1c
        - weight: 1  #this is weight preference, higher weight means higher preference. If the node has this label, the pod will be scheduled on that node. If not, it will be scheduled on any other node.
          preference:
            matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - us-east-1a