apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-pod
  labels:
    project: roboshop
    component: frontend
spec:
  containers:
    - name: pod-affinity-container
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-pod-2
  labels:
    project: roboshop
    component: backend 
spec:
  containers:
    - name: pod-affinity-container
      image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: component
                operator: In
                values:
                  - frontend
          topologyKey: topology.kubernetes.io/zone # this is the boarder of the node, 
          #the pod will be scheduled on the node with this label. with in the same zone, the pod will be scheduled on the node with the pod that has the label component=frontend