apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-pod
  labels:
    project: roboshop
    component: pod-affinity
spec:
  containers:
    - name: pod-affinity-container
      image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: project
                operator: In
                values:
                  - roboshop

          topologyKey: kubernetes.io/hostname