apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-pod
  labels:
    project: roboshop
    component: pod-affinity
spec:
  containers:
    - name: pod-affinity-container
      image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: project
                operator: In
                values:
                  - roboshop
          topologyKey: kubernetes.io/hostname # this is the boarder of the node, the pod will be scheduled on the node with this label. If the node does not have this label, the pod will not be scheduled on that node.
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: notIn
                      values:
                        - pod-affinity
                topologyKey: kubernetes.io/hostname # this is the boarder of the node, the pod will be scheduled on the node with this label. If the node does not have this label, the pod will not be scheduled on that node.