apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-pod-1
  labels: 
    project: roboshop
    component: backend
spec:
  containers:
    - name: pod-anti-affinity-container
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity-pod-2
  labels:
    project: roboshop
    component: backend 
spec:
  containers:
    - name: pod-anti-affinity-container
      image: nginx
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: component
                operator: In
                values:
                  - backend
          topologyKey: kubernetes.io/hostname # this is the boarder of the node, 
          #this pod will not be scheduled with in the node , we put on hostname because we want to make sure that the pod is not scheduled on the same node with the pod that has the label component=backend