pipeline {
    agent {
        node { label 'ROBOSHOP' } //## Agent Lable we will provide here
    }
    //Build Section
    stages {
        stage('Build') {
            steps {
                script {
                    sh """
                        echo "Building Stage"
                    """
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh """
                        echo "Building Testing"
                    """
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh """
                        echo "Building Deploy"
                    """
                }
            }
        }
    }
    //Post Build 
    post {
        always {
            echo "it will run always"
        }
        success {
            echo "I will run only success"
        }
        failure {
            echo "I will run if build failed "
        }
    }

}