pipeline {
    agent {
        node { label 'ROBOSHOP' } ## Agent Lable we will provide here
    }
    stages {
        stage('Build') {
            steps {
                script {
                    sh """
                        echo "Building Stage"
                    """
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh """
                        echo "Building Testing"
                    """
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh """
                        echo "Building Deploy"
                    """
                }
            }
        }
    }

}