[local]
localhost

[mongodb]
mongodb.azdevopsvenkat.site

[redis]
redis.azdevopsvenkat.site

[mysql]
mysql.azdevopsvenkat.site

[rabbitmq]
rabbitmq.azdevopsvenkat.site

[catalogue]
catalogue.azdevopsvenkat.site

[user]
user.azdevopsvenkat.site

[cart]
cart.azdevopsvenkat.site

[shipping]
shipping.azdevopsvenkat.site

[payment]
payment.azdevopsvenkat.site

[frontend]
frontend.azdevopsvenkat.site 