apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop     # The namespace where this role applies
  name: roboshop-trainee
rules:
- apiGroups: [""]         # The core/empty API group for Pods, Services, ConfigMaps, etc.
  resources: ["pods"]
  verbs: ["get", "list", "watch"] # Pod reader access 
