apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-trainees
  namespace: roboshop # Must match the namespace of the Role and ServiceAccount
subjects:
- kind: Group
  name: devops-trainers # Name of the Group 
  namespace: roboshop
roleRef:
  kind: Role # Must match the kind of role being referenced (Role or ClusterRole)
  name: devops-trainees # The exact name of the Role you created
  apiGroup: rbac.authorization.k8s.io
