### eksctl create accessentry  -f 03-accessEntrys.yaml 
## for creation of accessentry 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: roboshop    # Your EKS cluster name
  region: us-east-1                    # Target AWS region
# ACCESS MANAGEMENT CONFIGURATION
accessConfig:
  # it means we are using both aws-auth configmap, we are in the process of migrating to access entries.
  # new users follow API way, old users are following CONFIG_MAP way. priority is API
  # slowly we move old users to API way
  authenticationMode: API_AND_CONFIG_MAP # Migrates seamlessly from aws-auth configmap to EKS Access APIs
  accessEntries:
    # 1. Full Cluster Administrator Access (e.g., DevOps/Admin IAM Role)
    - principalARN: arn:aws:iam::453388807064:user/ram # Replace with your target Admin Role ARN
      type: STANDARD
      kubernetesGroups:   ## optional Kubernetes groups
        - devops-trainees # groups can used to give permissions via RBAC
    # 2. Scoped Access (e.g., Developer IAM User restricted to the 'roboshop' namespace)
    - principalARN: arn:aws:iam::453388807064:user/raheem # Replace with your target Developer IAM User ARN
      type: STANDARD
      kubernetesGroups:   ## optional Kubernetes groups
        - devops-trainees # groups can used to give permissions via RBAC