apiVersion: v1
kind: Pod
metadata:
  name: aws-cli # pod name
  labels:
    project: roboshop
    environment: dev
    purpose: poc
spec:
  containers:
  - name: aws-cli # container name
    image: amazon/aws-cli 
    command: ["sleep", "1000"]